### ISSUE TITLE
Reproducing results of Fig.5 in paper

### ISSUE THREAD

**Issue by Daideyun** [PRBonn/OverlapNet#13]
Hi!
Thanks for your awesome work!
I have some questions. When you use RangeNet + + to get semantic clues, Are the parameters of RangeNet++ same between KITTI sequence and Ford campus sequence? 
If It is different, how do I adjust parameters? 
Do I need to train the RangeNet++ by using Ford campus dataset?

**Comment by Chen-Xieyuanli** [comment]
Hey @Daideyun,

Thanks for following our work!

We didn't use the semantic information when testing on the Ford campus sequence and we found without semantic information our method also works well. 

Since the environment and the sensor setup are different between the KITTI and Ford campus dataset, you may need to fine-tune the model a little bit.

There were also other users who tried to use RangeNet++ on the ford campus dataset, where you may find more information: https://github.com/PRBonn/rangenet_lib/issues/28

I hope this helps!

**Comment by Daideyu** [comment]
Ok!
Thank you very much! @Chen-Xieyuanli

**Comment by Chen-Xieyuanli** [comment]
Thanks for the reply!

I'm about to close this issue. If there are further questions regarding this, please feel free to ask me to reopen it.
