### ISSUE TITLE
Questions about my test

### ISSUE THREAD

**Issue by hitbg-yjm** [PRBonn/OverlapNet#14]
Hi, I test OverlapNet in other datasets and the results are shown in the picture below.Robot is in the same place with different orientation. I want to know if the orientation will affect the output. Because the reality is that robot often come back to one place with different orientation.
![Screenshot from 2020-12-31 10-30-15](https://user-images.githubusercontent.com/64351196/103397937-60124900-4b75-11eb-9051-efee26fac20b.png)
![Screenshot from 2020-12-31 10-16-46](https://user-images.githubusercontent.com/64351196/103397940-6274a300-4b75-11eb-88e8-eef4a803d11a.png)

**Comment by Chen-Xieyuanli** [comment]
Hey @hitbg-yjm,

Happy New Year! Thanks for following our work!

That's a good question. Theoretically, the overlap estimation should be invariant to the rotation as can be seen from the eq3 in the paper. However, since we trained the two heads together, the correlation head will also affect the weights of the legs too.

There is a similar issue #12 discussing the rotation invariant problem which you may find useful. It's also about how to make the overlap prediction less influenced by the orientation which is actually to use the rotation augmentation during the training process.

I hope my answer helps!

**Comment by hitbg-yjm** [comment]
Thanks for your answer! And Happy New Year!
